apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
  labels:
    app: discord-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      name: discord-bot
      labels:
        app: discord-bot
    spec:
      containers:
        - name: discord-bot
          image: ghcr.io/zgamelogic/discord-bot:master
          imagePullPolicy: Always
          volumeMounts:
            - name: keystore-volume
              mountPath: "/etc/keystore"
              readOnly: true
          env:
            - name: TZ
              value: "America/Chicago"
      volumes:
        - name: keystore-volume
          secret:
            secretName: ssl-keystore-secret
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-secret
