name: Docker Image CI

on:
  push:
    branches: [ "master" ]
jobs:
  deploy:
    permissions:
      contents: read
      packages: write
    uses: zgamelogic/github-actions/.github/workflows/kubernetes-deploy.yaml@main
    with:
      applicationId: 1
      monitorIds: '1'
      environment: production
      deploymentName: discord-bot
      imageName: discord-bot